# Generated by Django 4.2.2 on 2023-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='brand',
        ),
        migrations.AddField(
            model_name='website',
            name='banner',
            field=models.ImageField(blank=True, upload_to='imgs/banner_imgs/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, upload_to='imgs/web_imgs/'),
        ),
    ]
