# Generated by Django 4.2.2 on 2023-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_website_brand_website_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='website',
            name='category',
        ),
        migrations.AddField(
            model_name='website',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
