# Generated by Django 4.2.2 on 2023-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_website_banner_remove_website_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.ManyToManyField(to='apis.category'),
        ),
    ]
