# Generated by Django 4.2.2 on 2023-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_website_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.ManyToManyField(to='apis.category'),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.URLField(),
        ),
    ]
