# Generated by Django 4.2.2 on 2023-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_website_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
