# Generated by Django 4.2.2 on 2023-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_website_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='banners',
            field=models.TextField(blank=True),
        ),
    ]
