# Generated by Django 4.2.2 on 2023-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_website_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='banners',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
